-- ==============================================================================
-- Craft Studio & Supabase Schema
-- Project: https://jyliqmshfkszdxlndvdb.supabase.co
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/jyliqmshfkszdxlndvdb/sql/new
-- ==============================================================================

-- 1. Create Public User Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  plan TEXT DEFAULT 'Free Trial',
  role TEXT DEFAULT 'user', -- 'admin' | 'user'
  avatar_url TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Public Form Submissions & Leads Table
CREATE TABLE IF NOT EXISTS public.submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_slug TEXT NOT NULL,
  form_type TEXT NOT NULL,
  name TEXT,
  email TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Cloud Projects Table (Multi-Project Storage & Autosave)
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Untitled Project',
  slug TEXT UNIQUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  thumbnail_url TEXT,
  is_public BOOLEAN DEFAULT false,
  version INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Project Revisions Table (Version History & Point-in-time Rollbacks)
CREATE TABLE IF NOT EXISTS public.project_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
  name TEXT DEFAULT 'Auto-save revision',
  data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_revisions ENABLE ROW LEVEL SECURITY;

-- 6. Policies for profiles
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" 
  ON public.profiles FOR SELECT 
  TO authenticated 
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" 
  ON public.profiles FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = id);

-- 7. Policies for submissions (Leads)
DROP POLICY IF EXISTS "Anyone can submit leads" ON public.submissions;
CREATE POLICY "Anyone can submit leads" 
  ON public.submissions FOR INSERT 
  TO anon, authenticated 
  WITH CHECK (true);

-- 8. Policies for projects
-- Authenticated users can view their own projects; public can view if is_public = true or unassigned
DROP POLICY IF EXISTS "Users can view accessible projects" ON public.projects;
CREATE POLICY "Users can view accessible projects"
  ON public.projects FOR SELECT
  TO anon, authenticated
  USING (
    is_public = true 
    OR user_id IS NULL 
    OR (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  );

-- Users can insert projects
DROP POLICY IF EXISTS "Users can insert projects" ON public.projects;
CREATE POLICY "Users can insert projects"
  ON public.projects FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    user_id IS NULL 
    OR (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  );

-- Users can update their own projects or unassigned projects
DROP POLICY IF EXISTS "Users can update projects" ON public.projects;
CREATE POLICY "Users can update projects"
  ON public.projects FOR UPDATE
  TO anon, authenticated
  USING (
    user_id IS NULL 
    OR (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  );

-- Users can delete their own projects
DROP POLICY IF EXISTS "Users can delete projects" ON public.projects;
CREATE POLICY "Users can delete projects"
  ON public.projects FOR DELETE
  TO anon, authenticated
  USING (
    user_id IS NULL 
    OR (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  );

-- 9. Policies for project revisions
DROP POLICY IF EXISTS "Users can view project revisions" ON public.project_revisions;
CREATE POLICY "Users can view project revisions"
  ON public.project_revisions FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = project_revisions.project_id
        AND (p.is_public = true OR p.user_id IS NULL OR p.user_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users can insert project revisions" ON public.project_revisions;
CREATE POLICY "Users can insert project revisions"
  ON public.project_revisions FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = project_revisions.project_id
        AND (p.user_id IS NULL OR p.user_id = auth.uid())
    )
  );

-- 10. Trigger to automatically create a profile when a new user signs up in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, plan, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'plan', 'Free Trial'),
    'user'
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger cleanly
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- Success! Tables (profiles, submissions, projects, project_revisions) are defined.
-- ==============================================================================
