-- ==============================================================================
-- Craft Studio & Supabase Schema
-- Project: https://jyliqmshfkszdxlndvdb.supabase.co
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/jyliqmshfkszdxlndvdb/sql/new
-- ==============================================================================

-- 1. Create Public User Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  plan TEXT DEFAULT 'Free Trial',
  role TEXT DEFAULT 'user', -- 'admin' | 'user'
  avatar_url TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Public Form Submissions & Leads Table
CREATE TABLE IF NOT EXISTS public.submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_slug TEXT NOT NULL,
  form_type TEXT NOT NULL,
  name TEXT,
  email TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS) for bulletproof privacy
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- 4. Policies for profiles
-- Authenticated users can read their own profile
CREATE POLICY "Users can view own profile" 
  ON public.profiles FOR SELECT 
  TO authenticated 
  USING (auth.uid() = id);

-- Authenticated users can update their own profile
CREATE POLICY "Users can update own profile" 
  ON public.profiles FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = id);

-- 5. Policies for submissions (Leads)
-- Anyone (including anonymous visitors on landing page) can submit forms
CREATE POLICY "Anyone can submit leads" 
  ON public.submissions FOR INSERT 
  TO anon, authenticated 
  WITH CHECK (true);

-- 6. Trigger to automatically create a profile when a new user signs up in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, plan, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'plan', 'Free Trial'),
    'user'
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger cleanly
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- Success! Tables (profiles, submissions) and auto-sync triggers are active.
-- ==============================================================================
