import type { CanvasElement, ProjectState, ElementType } from '../types/editor';
import { LANDING_PAGE_ELEMENTS } from './landingPageElements';

export const CANVAS_DEFAULT_WIDTH = 1200;
export const CANVAS_DEFAULT_HEIGHT = 800;
export const STORAGE_KEY = 'visual_website_builder_project_v14';

export const COLOR_PALETTES = [
  '#0f172a', '#1e293b', '#334155', '#475569', '#64748b', '#94a3b8', '#cbd5e1', '#f1f5f9', '#ffffff',
  '#2563eb', '#3b82f6', '#60a5fa', '#93c5fd', '#dbeafe',
  '#4f46e5', '#6366f1', '#818cf8', '#a5b4fc', '#e0e7ff',
  '#059669', '#10b981', '#34d399', '#6ee7b7', '#d1fae5',
  '#d97706', '#f59e0b', '#fbbf24', '#fde68a', '#fef3c7',
  '#dc2626', '#ef4444', '#f87171', '#fca5a5', '#fee2e2',
  '#9333ea', '#a855f7', '#c084fc', '#e9d5ff', '#fae8ff',
  '#0d9488', '#14b8a6', '#2dd4bf', '#99f6e4', '#ccfbf1'
];

export const FONT_FAMILIES = [
  { label: 'Inter (Sans)', value: 'Inter, -apple-system, sans-serif' },
  { label: 'Plus Jakarta Sans', value: "'Plus Jakarta Sans', sans-serif" },
  { label: 'System Sans', value: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" },
  { label: 'JetBrains Mono', value: "'JetBrains Mono', monospace" },
  { label: 'Serif Classic', value: "Georgia, Cambria, 'Times New Roman', serif" },
];

export function generateId(): string {
  return 'el_' + Math.random().toString(36).substring(2, 9) + '_' + Date.now().toString(36);
}

export function createElement(
  type: ElementType,
  x = 100,
  y = 100,
  zIndexOrParentIdOrOverrides?: number | string | Partial<CanvasElement>,
  optionalParentId?: string | null,
  extraOverrides?: Partial<CanvasElement>
): CanvasElement {
  const isArg4Object =
    typeof zIndexOrParentIdOrOverrides === 'object' && zIndexOrParentIdOrOverrides !== null;
  const overrides: Partial<CanvasElement> | undefined = isArg4Object
    ? (zIndexOrParentIdOrOverrides as Partial<CanvasElement>)
    : extraOverrides;

  const id = overrides?.id || generateId();
  const zIndex =
    typeof zIndexOrParentIdOrOverrides === 'number'
      ? zIndexOrParentIdOrOverrides
      : overrides?.zIndex ?? 1;
  const parentId =
    typeof zIndexOrParentIdOrOverrides === 'string'
      ? zIndexOrParentIdOrOverrides
      : overrides?.parentId !== undefined
      ? overrides.parentId
      : optionalParentId ?? null;

  const buildElement = (): CanvasElement => {
    switch (type) {
    case 'section':
      return {
        id,
        name: 'New Section',
        type: 'section',
        x,
        y,
        width: 1120,
        height: 360,
        styles: {
          backgroundColor: '#ffffff',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#e2e8f0',
          boxShadow: '0 4px 14px rgba(15, 23, 42, 0.03)',
          opacity: 1,
        },
        role: 'container',
        behavior: {
          actionType: 'none',
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        children: [],
        layout: {
          layoutType: 'flex',
          direction: 'column',
          alignItems: 'start',
          justifyContent: 'start',
          gap: 20,
          padding: { top: 32, right: 32, bottom: 32, left: 32 },
          responsiveDirection: {
            tablet: 'column',
            mobile: 'column',
          },
        },
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'full-width', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'container':
      return {
        id,
        name: 'Card Container',
        type: 'container',
        x,
        y,
        width: 320,
        height: 220,
        styles: {
          backgroundColor: '#ffffff',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#e2e8f0',
          boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.06), 0 8px 10px -6px rgba(0, 0, 0, 0.04)',
          opacity: 1,
        },
        role: 'card',
        behavior: {
          actionType: 'none',
          hoverStyles: {
            borderColor: '#3b82f6',
            scale: 1.01,
          },
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        children: [],
        layout: {
          layoutType: 'flex',
          direction: 'column',
          alignItems: 'start',
          justifyContent: 'start',
          gap: 16,
          padding: { top: 20, right: 20, bottom: 20, left: 20 },
          responsiveDirection: {
            tablet: 'column',
            mobile: 'column',
          },
        },
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'stack', visible: true },
          locked: false,
        },
      };

    case 'text':
      return {
        id,
        name: 'Heading / Text',
        type: 'text',
        x,
        y,
        width: 380,
        height: 54,
        content: 'Design it. Define it. Ship it.',
        styles: {
          color: '#0f172a',
          fontSize: 32,
          fontWeight: 700,
          fontFamily: "'Plus Jakarta Sans', sans-serif",
          textAlign: 'left',
          lineHeight: 1.2,
          backgroundColor: 'transparent',
          opacity: 1,
        },
        role: 'text',
        behavior: {
          actionType: 'none',
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'button':
      return {
        id,
        name: 'Interactive Button',
        type: 'button',
        x,
        y,
        width: 170,
        height: 48,
        content: 'Get Started →',
        styles: {
          backgroundColor: '#6366f1',
          color: '#ffffff',
          fontSize: 14,
          fontWeight: 600,
          fontFamily: 'Inter, -apple-system, sans-serif',
          textAlign: 'center',
          borderRadius: 8,
          borderWidth: 0,
          borderStyle: 'none',
          borderColor: 'transparent',
          boxShadow: '0 4px 14px 0 rgba(99, 102, 241, 0.35)',
          opacity: 1,
          hoverEffect: 'lift',
        },
        role: 'button',
        behavior: {
          actionType: 'navigate-page',
          actionPayload: '__next__',
          hoverStyles: {
            backgroundColor: '#4f46e5',
            scale: 1.03,
          },
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'image':
      return {
        id,
        name: 'Visual Image',
        type: 'image',
        x,
        y,
        width: 360,
        height: 240,
        content: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
        styles: {
          borderRadius: 12,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#e2e8f0',
          boxShadow: '0 10px 20px -3px rgba(0, 0, 0, 0.08)',
          objectFit: 'cover',
          opacity: 1,
          backgroundColor: '#f1f5f9',
        },
        role: 'image',
        behavior: {
          actionType: 'none',
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'divider':
      return {
        id,
        name: 'Horizontal Divider',
        type: 'divider',
        x,
        y,
        width: 400,
        height: 2,
        styles: {
          backgroundColor: '#e2e8f0',
          dividerHeight: 2,
          opacity: 1,
        },
        role: 'none',
        behavior: {
          actionType: 'none',
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'shape':
      return {
        id,
        name: 'Geometric Shape',
        type: 'shape',
        x,
        y,
        width: 120,
        height: 120,
        styles: {
          backgroundColor: '#6366f1',
          shapeKind: 'circle',
          borderColor: '#4338ca',
          borderWidth: 0,
          opacity: 1,
          boxShadow: '0 8px 24px -4px rgba(99, 102, 241, 0.35)',
        },
        role: 'none',
        behavior: {
          actionType: 'none',
        },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'input':
      return {
        id,
        name: 'Input Field',
        type: 'input',
        x,
        y,
        width: 280,
        height: 44,
        content: '',
        formConfig: {
          inputType: 'text',
          fieldName: 'field_' + id.slice(-4),
          placeholder: 'Enter text...',
          required: false,
        },
        styles: {
          backgroundColor: '#181b26',
          color: '#ffffff',
          fontSize: 14,
          borderRadius: 8,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#2d3748',
          opacity: 1,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'textarea':
      return {
        id,
        name: 'Message Area',
        type: 'textarea',
        x,
        y,
        width: 280,
        height: 100,
        content: '',
        formConfig: {
          inputType: 'text',
          fieldName: 'message_' + id.slice(-4),
          placeholder: 'Type your message...',
          required: false,
        },
        styles: {
          backgroundColor: '#181b26',
          color: '#ffffff',
          fontSize: 14,
          borderRadius: 8,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#2d3748',
          opacity: 1,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'select':
      return {
        id,
        name: 'Dropdown Select',
        type: 'select',
        x,
        y,
        width: 280,
        height: 44,
        content: '',
        formConfig: {
          fieldName: 'choice_' + id.slice(-4),
          options: ['Option 1', 'Option 2', 'Option 3'],
          required: false,
        },
        styles: {
          backgroundColor: '#181b26',
          color: '#ffffff',
          fontSize: 14,
          borderRadius: 8,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#2d3748',
          opacity: 1,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'checkbox':
      return {
        id,
        name: 'Checkbox Field',
        type: 'checkbox',
        x,
        y,
        width: 200,
        height: 36,
        content: 'I agree to the terms',
        formConfig: {
          fieldName: 'agree_' + id.slice(-4),
          checked: false,
          required: false,
        },
        styles: {
          color: '#ffffff',
          fontSize: 13,
          opacity: 1,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'form':
      return {
        id,
        name: 'Contact Form',
        type: 'form',
        x,
        y,
        width: 380,
        height: 320,
        styles: {
          backgroundColor: '#131620',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          boxShadow: '0 12px 32px rgba(0, 0, 0, 0.3)',
          opacity: 1,
        },
        role: 'form',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        children: [],
        layout: {
          layoutType: 'flex',
          direction: 'column',
          alignItems: 'start',
          justifyContent: 'start',
          gap: 16,
          padding: { top: 24, right: 24, bottom: 24, left: 24 },
        },
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'accordion':
      return {
        id,
        name: 'FAQ Accordion',
        type: 'accordion',
        x,
        y,
        width: 480,
        height: 260,
        styles: {
          backgroundColor: '#121520',
          borderRadius: 14,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          color: '#ffffff',
          boxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)',
          opacity: 1,
        },
        accordionConfig: {
          allowMultiple: false,
          items: [
            {
              id: 'item_1',
              title: 'How fast is deployment?',
              content: 'Deployment happens in sub-second time directly to high-availability edge networks worldwide.',
              isOpen: true,
            },
            {
              id: 'item_2',
              title: 'Can I connect a custom domain?',
              content: 'Yes! Connect any custom domain with automated zero-configuration SSL certificates.',
              isOpen: false,
            },
            {
              id: 'item_3',
              title: 'Is there a free trial?',
              content: 'You can start completely free with no credit card required and upgrade anytime.',
              isOpen: false,
            },
          ],
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'carousel':
      return {
        id,
        name: 'Image Carousel',
        type: 'carousel',
        x,
        y,
        width: 520,
        height: 320,
        styles: {
          backgroundColor: '#0c0e14',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          boxShadow: '0 12px 32px rgba(0, 0, 0, 0.35)',
          opacity: 1,
        },
        carouselConfig: {
          autoplay: true,
          interval: 4,
          showDots: true,
          showArrows: true,
          slides: [
            {
              id: 'slide_1',
              url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
              caption: 'Abstract Spatial Design',
            },
            {
              id: 'slide_2',
              url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80',
              caption: 'Future Tech Workspace',
            },
            {
              id: 'slide_3',
              url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
              caption: 'Vibrant Neo Palette',
            },
          ],
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'video':
      return {
        id,
        name: 'Video Player',
        type: 'video',
        x,
        y,
        width: 560,
        height: 315,
        styles: {
          backgroundColor: '#000000',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          boxShadow: '0 12px 36px rgba(0, 0, 0, 0.4)',
          opacity: 1,
        },
        videoConfig: {
          url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          videoType: 'youtube',
          autoplay: false,
          controls: true,
          muted: false,
          loop: false,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'counter':
      return {
        id,
        name: 'Stat Counter',
        type: 'counter',
        x,
        y,
        width: 200,
        height: 110,
        styles: {
          backgroundColor: '#121520',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
          color: '#ffffff',
          textAlign: 'center',
          opacity: 1,
        },
        counterConfig: {
          startValue: 0,
          targetValue: 99.9,
          prefix: '',
          suffix: '%',
          label: 'Uptime Reliability',
          duration: 2,
          decimals: 1,
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'product-card':
      return {
        id,
        name: 'Product Card',
        type: 'product-card',
        x,
        y,
        width: 320,
        height: 420,
        styles: {
          backgroundColor: '#121520',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f44',
          color: '#ffffff',
          boxShadow: '0 12px 32px rgba(0, 0, 0, 0.35)',
          opacity: 1,
        },
        productConfig: {
          productId: 'prod_aura_pro',
          title: 'Aura Studio Wireless',
          price: 199,
          compareAtPrice: 249,
          currency: '$',
          badge: 'BEST SELLER',
          imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
          buttonText: 'Add to Bag',
          variants: ['Matte Black', 'Lunar Silver', 'Cosmic Blue'],
          selectedVariant: 'Matte Black',
          inStock: true,
        },
        role: 'none',
        behavior: { actionType: 'add-to-cart' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'lottie':
      return {
        id,
        name: 'Lottie Animation',
        type: 'lottie',
        x,
        y,
        width: 240,
        height: 240,
        styles: {
          backgroundColor: 'transparent',
          borderRadius: 12,
          opacity: 1,
        },
        lottieConfig: {
          url: 'https://assets2.lottiefiles.com/packages/lf20_u4yrau.json',
          autoplay: true,
          loop: true,
          speed: 1,
          trigger: 'autoplay',
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    case 'poll':
      return {
        id,
        name: 'Live Visitor Poll',
        type: 'poll',
        x,
        y,
        width: 440,
        height: 320,
        styles: {
          backgroundColor: '#121624',
          borderRadius: 16,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262f46',
          color: '#ffffff',
          boxShadow: '0 12px 32px rgba(0, 0, 0, 0.3)',
          opacity: 1,
        },
        pollConfig: {
          question: 'What feature should we ship next? 🚀',
          themeColor: '#6366f1',
          allowMultiple: false,
          totalVotes: 154,
          options: [
            { id: 'opt_1', label: '⚡ Instant AI Publishing', votes: 42 },
            { id: 'opt_2', label: '🎨 3D Motion Canvas', votes: 28 },
            { id: 'opt_3', label: '🤝 Real-Time Multiplayer', votes: 65 },
            { id: 'opt_4', label: '📱 Native Mobile App', votes: 19 },
          ],
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'guestbook':
      return {
        id,
        name: 'Guestbook Wall',
        type: 'guestbook',
        x,
        y,
        width: 480,
        height: 420,
        styles: {
          backgroundColor: '#121522',
          borderRadius: 18,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#262e46',
          color: '#ffffff',
          boxShadow: '0 16px 36px rgba(0, 0, 0, 0.35)',
          opacity: 1,
        },
        guestbookConfig: {
          title: 'Visitor Guestbook & Wall 💌',
          subtitle: 'Leave a shoutout, feedback, or say hi!',
          allowSubmissions: true,
          maxEntries: 20,
          entries: [
            {
              id: 'gb_1',
              name: 'Sarah Chen',
              message: 'The interactive widgets are so buttery smooth! Love this! 🔥',
              avatarEmoji: '🚀',
              date: 'Just now',
              likes: 12,
            },
            {
              id: 'gb_2',
              name: 'Alex Rivera',
              message: 'Built and launched my website in under 5 minutes. Incredible work!',
              avatarEmoji: '✨',
              date: '2h ago',
              likes: 8,
            },
            {
              id: 'gb_3',
              name: 'Liam Vance',
              message: 'Loving the kid-friendly mode! My students made their own games page 🎮',
              avatarEmoji: '🥒',
              date: 'Yesterday',
              likes: 15,
            },
          ],
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'full-width', visible: true },
          locked: false,
        },
      };

    case 'reaction':
      return {
        id,
        name: 'Reaction Button',
        type: 'reaction',
        x,
        y,
        width: 180,
        height: 56,
        styles: {
          backgroundColor: '#181c2b',
          borderRadius: 999,
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#313b59',
          color: '#ffffff',
          boxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)',
          opacity: 1,
        },
        reactionConfig: {
          emoji: '🔥',
          label: 'Hype',
          count: 128,
          burstType: 'confetti',
          soundEffect: 'pop',
        },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };

    default:
      return {
        id,
        name: 'Element',
        type: 'container',
        x,
        y,
        width: 100,
        height: 100,
        styles: { opacity: 1 },
        role: 'none',
        behavior: { actionType: 'none' },
        locked: false,
        zIndex,
        parentId: parentId ?? null,
        responsive: {
          desktop: { mode: 'auto' },
          tablet: { mode: 'auto', visible: true },
          mobile: { mode: 'auto', visible: true },
          locked: false,
        },
      };
    }
  };

  const base = buildElement();
  if (!overrides) return base;

  return {
    ...base,
    ...overrides,
    styles: {
      ...base.styles,
      ...(overrides.styles || {}),
    },
    behavior: {
      ...base.behavior,
      ...(overrides.behavior || {}),
    },
    responsive: {
      ...base.responsive,
      ...(overrides.responsive || {}),
    },
  };
}

export const INITIAL_PROJECT: ProjectState = {
  version: 1,
  id: 'proj_default_01',
  name: 'Untitled Project',
  activePageId: 'page_home',
  updatedAt: new Date().toISOString(),
  pages: [
    {
      id: 'page_home',
      name: 'Home',
      slug: '/',
      canvasWidth: CANVAS_DEFAULT_WIDTH,
      canvasHeight: 4300,
      backgroundColor: '#0c0e14',
      elements: LANDING_PAGE_ELEMENTS,
    },
    {
      id: 'page_about',
      name: 'About',
      slug: '/about',
      canvasWidth: CANVAS_DEFAULT_WIDTH,
      canvasHeight: 700,
      backgroundColor: '#f8fafc',
      elements: [
        {
          id: 'el_about_back',
          name: 'Back to Home Button',
          type: 'button',
          x: 60,
          y: 50,
          width: 140,
          height: 40,
          content: '← Back to Home',
          styles: {
            backgroundColor: '#ffffff',
            color: '#0f172a',
            fontSize: 13,
            fontWeight: 600,
            borderRadius: 8,
            borderWidth: 1,
            borderStyle: 'solid',
            borderColor: '#e2e8f0',
            opacity: 1,
          },
          role: 'button',
          behavior: {
            actionType: 'navigate-page',
            actionPayload: 'page_home',
            hoverStyles: {
              backgroundColor: '#f1f5f9',
            },
          },
          locked: false,
          zIndex: 1,
        },
        {
          id: 'el_about_heading',
          name: 'About Heading',
          type: 'text',
          x: 60,
          y: 130,
          width: 600,
          height: 60,
          content: 'About Our Visual Builder',
          styles: {
            color: '#0f172a',
            fontSize: 36,
            fontWeight: 800,
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            opacity: 1,
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 2,
        },
        {
          id: 'el_about_body',
          name: 'About Description',
          type: 'text',
          x: 60,
          y: 210,
          width: 640,
          height: 120,
          content: 'We believe creating websites visually should never sacrifice structure or semantics. Every visual element you position is rooted in standard web primitives, ensuring your visual intent translates into clean semantic meaning.',
          styles: {
            color: '#475569',
            fontSize: 16,
            lineHeight: 1.6,
            opacity: 1,
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
        },
      ],
    },
    {
      id: 'page_signup',
      name: 'Sign Up',
      slug: '/signup',
      canvasWidth: CANVAS_DEFAULT_WIDTH,
      canvasHeight: 900,
      backgroundColor: '#0a0d14',
      elements: [
        {
          id: 'el_su_nav',
          name: 'Floating Glass Navbar',
          type: 'section',
          x: 40,
          y: 24,
          width: 1120,
          height: 64,
          role: 'navigation',
          layout: {
            layoutType: 'flex',
            direction: 'row',
            align: 'center',
            alignItems: 'center',
            justify: 'space-between',
            justifyContent: 'space-between',
            gap: 16,
            padding: { top: 14, right: 28, bottom: 14, left: 28 },
          },
          styles: {
            backgroundColor: '#11141d',
            borderRadius: 12,
            borderWidth: 1,
            borderStyle: 'solid',
            borderColor: '#232c3f',
            boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
          },
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 1,
          children: ['el_su_logo', 'el_su_back_btn'],
        },
        {
          id: 'el_su_logo',
          name: 'Brand Logo',
          type: 'text',
          x: 68,
          y: 40,
          width: 200,
          height: 32,
          content: '🥒 PICKLE CORP',
          styles: {
            fontSize: 15,
            fontWeight: 800,
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            color: '#ffffff',
          },
          role: 'text',
          behavior: { actionType: 'navigate-page', actionPayload: 'page_home' },
          locked: false,
          zIndex: 2,
          parentId: 'el_su_nav',
        },
        {
          id: 'el_su_back_btn',
          name: 'Back to Home Button',
          type: 'button',
          x: 960,
          y: 36,
          width: 140,
          height: 38,
          content: '← Back to Home',
          styles: {
            backgroundColor: 'rgba(255, 255, 255, 0.06)',
            borderColor: 'rgba(255, 255, 255, 0.15)',
            borderWidth: 1,
            borderStyle: 'solid',
            color: '#e2e8f0',
            borderRadius: 8,
            fontSize: 12,
            fontWeight: 600,
          },
          role: 'button',
          behavior: { actionType: 'navigate-page', actionPayload: 'page_home' },
          locked: false,
          zIndex: 2,
          parentId: 'el_su_nav',
        },
        {
          id: 'el_su_split_hero',
          name: 'Sign-Up Split Hero',
          type: 'section',
          x: 40,
          y: 110,
          width: 1120,
          height: 680,
          role: 'container',
          layout: {
            layoutType: 'flex',
            direction: 'row',
            align: 'center',
            alignItems: 'center',
            justify: 'space-between',
            justifyContent: 'space-between',
            gap: 40,
            padding: { top: 32, right: 32, bottom: 32, left: 32 },
            responsiveDirection: { tablet: 'column', mobile: 'column' },
          },
          styles: {
            backgroundColor: 'transparent',
            borderWidth: 0,
            borderStyle: 'none',
          },
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 1,
          children: ['el_su_left_col', 'el_su_card'],
        },
        {
          id: 'el_su_left_col',
          name: 'Sign-Up Info Column',
          type: 'container',
          x: 60,
          y: 130,
          width: 520,
          height: 600,
          role: 'container',
          layout: {
            layoutType: 'flex',
            direction: 'column',
            align: 'start',
            alignItems: 'start',
            justify: 'center',
            justifyContent: 'center',
            gap: 16,
            padding: { top: 16, right: 16, bottom: 16, left: 16 },
          },
          styles: {
            backgroundColor: 'transparent',
            borderWidth: 0,
            boxShadow: 'none',
          },
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 2,
          parentId: 'el_su_split_hero',
          children: ['el_su_badge', 'el_su_title', 'el_su_desc', 'el_su_perks', 'el_su_stars'],
        },
        {
          id: 'el_su_badge',
          name: 'Free Trial Badge',
          type: 'text',
          x: 76,
          y: 150,
          width: 220,
          height: 28,
          content: '✨ 14-DAY RISK-FREE TRIAL',
          styles: {
            fontSize: 11,
            fontWeight: 700,
            color: '#38bdf8',
            backgroundColor: 'rgba(14, 165, 233, 0.15)',
            borderColor: 'rgba(14, 165, 233, 0.35)',
            borderWidth: 1,
            borderStyle: 'solid',
            borderRadius: 9999,
            textAlign: 'center',
            lineHeight: 2.3,
          },
          role: 'badge',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_left_col',
        },
        {
          id: 'el_su_title',
          name: 'Sign-Up Headline',
          type: 'text',
          x: 76,
          y: 195,
          width: 500,
          height: 100,
          content: 'Join 25,000+ Modern Creators Building with Visual Agility',
          styles: {
            fontSize: 34,
            fontWeight: 800,
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            color: '#ffffff',
            lineHeight: 1.2,
          },
          role: 'heading-h1',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_left_col',
        },
        {
          id: 'el_su_desc',
          name: 'Sign-Up Subtitle',
          type: 'text',
          x: 76,
          y: 310,
          width: 480,
          height: 52,
          content: 'Design beautiful, responsive web experiences with zero friction. Includes real SQLite database and production code export.',
          styles: {
            fontSize: 14,
            color: '#94a3b8',
            lineHeight: 1.6,
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_left_col',
        },
        {
          id: 'el_su_perks',
          name: 'Feature Perks List',
          type: 'text',
          x: 76,
          y: 375,
          width: 480,
          height: 130,
          content: '✓ Zero-setup SQLite database integration\n✓ Full drag-and-drop canvas with magnetic snap\n✓ Clean HTML5 & CSS export with native responsive reflow\n✓ Unlimited pages and custom templates',
          styles: {
            fontSize: 13,
            color: '#cbd5e1',
            lineHeight: 2.0,
            fontFamily: "'Inter', sans-serif",
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_left_col',
        },
        {
          id: 'el_su_stars',
          name: 'Trust Rating',
          type: 'text',
          x: 76,
          y: 520,
          width: 400,
          height: 30,
          content: '★★★★★  4.9/5 from 1,200+ verified developers & designers',
          styles: {
            fontSize: 12,
            color: '#fbbf24',
            fontWeight: 600,
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_left_col',
        },
        {
          id: 'el_su_card',
          name: 'Sign-Up Registration Card',
          type: 'container',
          x: 620,
          y: 130,
          width: 460,
          height: 580,
          role: 'card',
          layout: {
            layoutType: 'flex',
            direction: 'column',
            align: 'center',
            alignItems: 'center',
            justify: 'start',
            justifyContent: 'start',
            gap: 12,
            padding: { top: 32, right: 32, bottom: 32, left: 32 },
          },
          styles: {
            backgroundColor: '#131620',
            borderColor: '#242a3e',
            borderWidth: 1,
            borderStyle: 'solid',
            borderRadius: 16,
            boxShadow: '0 20px 50px -10px rgba(0, 0, 0, 0.7)',
          },
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 2,
          parentId: 'el_su_split_hero',
          children: [
            'el_su_form_title',
            'el_su_form_sub',
            'el_su_in_name',
            'el_su_in_email',
            'el_su_in_pwd',
            'el_su_btn_submit',
            'el_su_terms',
            'el_su_login_link',
          ],
        },
        {
          id: 'el_su_form_title',
          name: 'Form Title',
          type: 'text',
          x: 652,
          y: 162,
          width: 396,
          height: 36,
          content: 'Create Your Free Account',
          styles: {
            fontSize: 22,
            fontWeight: 800,
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            textAlign: 'center',
            color: '#ffffff',
          },
          role: 'heading-h2',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_form_sub',
          name: 'Form Subtitle',
          type: 'text',
          x: 652,
          y: 202,
          width: 396,
          height: 24,
          content: 'Start building and shipping visual experiences instantly.',
          styles: {
            fontSize: 12,
            color: '#94a3b8',
            textAlign: 'center',
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_in_name',
          name: 'Full Name Input Field',
          type: 'container',
          x: 652,
          y: 236,
          width: 396,
          height: 44,
          content: 'Full Name (e.g. Alex Morgan)',
          styles: {
            backgroundColor: '#0a0c12',
            borderColor: '#272d42',
            borderWidth: 1,
            borderStyle: 'solid',
            borderRadius: 8,
            color: '#64748b',
            fontSize: 13,
            padding: 12,
          },
          role: 'input',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_in_email',
          name: 'Work Email Input Field',
          type: 'container',
          x: 652,
          y: 292,
          width: 396,
          height: 44,
          content: 'name@company.com',
          styles: {
            backgroundColor: '#0a0c12',
            borderColor: '#272d42',
            borderWidth: 1,
            borderStyle: 'solid',
            borderRadius: 8,
            color: '#64748b',
            fontSize: 13,
            padding: 12,
          },
          role: 'input',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_in_pwd',
          name: 'Password Input Field',
          type: 'container',
          x: 652,
          y: 348,
          width: 396,
          height: 44,
          content: '•••••••• (min 8 characters)',
          styles: {
            backgroundColor: '#0a0c12',
            borderColor: '#272d42',
            borderWidth: 1,
            borderStyle: 'solid',
            borderRadius: 8,
            color: '#64748b',
            fontSize: 13,
            padding: 12,
          },
          role: 'input',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_btn_submit',
          name: 'Create Free Account Button',
          type: 'button',
          x: 652,
          y: 406,
          width: 396,
          height: 48,
          content: 'Create Free Account →',
          styles: {
            backgroundColor: '#4f46e5',
            color: '#ffffff',
            borderRadius: 8,
            fontWeight: 700,
            fontSize: 14,
            boxShadow: '0 4px 16px rgba(79, 70, 229, 0.45)',
          },
          role: 'button',
          behavior: {
            actionType: 'alert',
            actionPayload: '✨ Registration submitted! Account registered to Supabase Cloud Auth & SQLite database.',
            hoverStyles: {
              backgroundColor: '#6366f1',
              scale: 1.02,
            },
          },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_terms',
          name: 'Terms & Privacy Note',
          type: 'text',
          x: 652,
          y: 468,
          width: 396,
          height: 32,
          content: 'By clicking Create Account, you agree to our Terms of Service & Privacy Policy.',
          styles: {
            fontSize: 11,
            color: '#64748b',
            textAlign: 'center',
            lineHeight: 1.4,
          },
          role: 'text',
          behavior: { actionType: 'none' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
        {
          id: 'el_su_login_link',
          name: 'Sign-In Switch Link',
          type: 'text',
          x: 652,
          y: 508,
          width: 396,
          height: 24,
          content: 'Already have an account? Sign in here →',
          styles: {
            fontSize: 12,
            color: '#818cf8',
            textAlign: 'center',
            fontWeight: 600,
          },
          role: 'link',
          behavior: { actionType: 'navigate-page', actionPayload: 'page_home' },
          locked: false,
          zIndex: 3,
          parentId: 'el_su_card',
        },
      ],
    },
  ],
};

export const BLANK_PAGE_ELEMENTS: CanvasElement[] = [];
