import type { CanvasElement } from '../types/editor';

/**
 * World-Class SaaS Landing Page with everything:
 * - Floating Glassmorphism Navbar with Logo, Navigation Links & Primary Sign-Up Button
 * - High-Impact Hero Section with announcement badge, headline, subtitle, dual CTAs & UI preview card
 * - Trusted Companies / Client Logos Social Proof Strip
 * - Bento Features Grid with 6 rich capability cards (including el_card_1, el_card_2, el_card_3)
 * - Interactive Lead Capture & Sign-Up Form Card with Name, Email, Password, and Submit button
 * - Client Testimonials & Social Proof Grid with 5-star review cards
 * - 3-Tier Pricing Comparison Table (Starter, Pro [Popular], Enterprise)
 * - Frequently Asked Questions (FAQ Accordion Cards)
 * - Radiant Gradient Bottom CTA Banner
 * - Comprehensive 4-Column Footer with brand summary, links, and copyright
 */
export const LANDING_PAGE_ELEMENTS: CanvasElement[] = [
  /* ========================================================================== */
  /* 1. FLOATING GLASS NAVBAR                                                   */
  /* ========================================================================== */
  {
    id: 'el_navbar',
    name: 'Floating Glass Navbar',
    type: 'container',
    x: 40,
    y: 20,
    width: 1120,
    height: 64,
    styles: {
      backgroundColor: '#11141d',
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      boxShadow: '0 8px 30px rgba(0, 0, 0, 0.45)',
      opacity: 1,
    },
    role: 'navigation',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 30,
    children: [
      'el_nav_logo',
      'el_nav_features',
      'el_nav_solutions',
      'el_nav_pricing',
      'el_nav_faq',
      'el_nav_link_about',
      'el_nav_cta',
    ],
  },
  {
    id: 'el_nav_logo',
    name: 'Brand Logo',
    type: 'text',
    parentId: 'el_navbar',
    x: 64,
    y: 35,
    width: 180,
    height: 34,
    content: '✦ CRAFT STUDIO',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'left',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 31,
  },
  {
    id: 'el_nav_features',
    name: 'Nav - Features',
    type: 'text',
    parentId: 'el_navbar',
    x: 430,
    y: 42,
    width: 75,
    height: 22,
    content: 'Features',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: '#features',
      hoverStyles: { color: '#ffffff' },
    },
    locked: false,
    zIndex: 32,
  },
  {
    id: 'el_nav_solutions',
    name: 'Nav - Solutions',
    type: 'text',
    parentId: 'el_navbar',
    x: 520,
    y: 42,
    width: 80,
    height: 22,
    content: 'Solutions',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: '#solutions',
      hoverStyles: { color: '#ffffff' },
    },
    locked: false,
    zIndex: 32,
  },
  {
    id: 'el_nav_pricing',
    name: 'Nav - Pricing',
    type: 'text',
    parentId: 'el_navbar',
    x: 615,
    y: 42,
    width: 65,
    height: 22,
    content: 'Pricing',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: '#pricing',
      hoverStyles: { color: '#ffffff' },
    },
    locked: false,
    zIndex: 32,
  },
  {
    id: 'el_nav_faq',
    name: 'Nav - FAQ',
    type: 'text',
    parentId: 'el_navbar',
    x: 695,
    y: 42,
    width: 55,
    height: 22,
    content: 'FAQ',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: '#faq',
      hoverStyles: { color: '#ffffff' },
    },
    locked: false,
    zIndex: 32,
  },
  {
    id: 'el_nav_link_about',
    name: 'Nav - Log In',
    type: 'text',
    parentId: 'el_navbar',
    x: 875,
    y: 42,
    width: 70,
    height: 22,
    content: 'Log in',
    styles: {
      color: '#cbd5e1',
      fontSize: 13,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: '#login',
      hoverStyles: { color: '#ffffff' },
    },
    locked: false,
    zIndex: 33,
  },
  {
    id: 'el_nav_cta',
    name: 'Nav - Sign Up Free Button',
    type: 'button',
    parentId: 'el_navbar',
    x: 960,
    y: 33,
    width: 175,
    height: 38,
    content: 'Sign Up Free →',
    styles: {
      gradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
      color: '#ffffff',
      fontSize: 13,
      fontWeight: 600,
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#818cf8',
      boxShadow: '0 0 20px rgba(99, 102, 241, 0.45)',
      opacity: 1,
      hoverEffect: 'lift',
      transitionDuration: 200,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: '🚀 Welcome to Craft Studio! Opening free account registration...',
    },
    locked: false,
    zIndex: 34,
  },

  /* ========================================================================== */
  /* 2. HIGH-IMPACT HERO SECTION                                               */
  /* ========================================================================== */
  {
    id: 'el_hero_badge',
    name: 'Hero Announcement Badge',
    type: 'text',
    x: 440,
    y: 110,
    width: 320,
    height: 30,
    content: '✨ CRAFT 3.0 • VISUAL WEBSITE BUILDER',
    styles: {
      fontSize: 11,
      fontWeight: 700,
      color: '#a5b4fc',
      backgroundColor: 'rgba(99, 102, 241, 0.16)',
      borderColor: 'rgba(99, 102, 241, 0.4)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.3,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_hero_heading',
    name: 'Hero Title',
    type: 'text',
    x: 160,
    y: 155,
    width: 880,
    height: 100,
    content: 'Build High-Impact Web Apps\nWithout Writing Code',
    styles: {
      color: '#ffffff',
      fontSize: 44,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', -apple-system, sans-serif",
      textAlign: 'center',
      lineHeight: 1.15,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_hero_sub',
    name: 'Hero Subtitle',
    type: 'text',
    x: 230,
    y: 270,
    width: 740,
    height: 52,
    content: 'The unified visual studio with native Supabase cloud data, automatic responsive layouts across all devices, and instant clean production HTML/CSS export.',
    styles: {
      color: '#94a3b8',
      fontSize: 15,
      fontWeight: 400,
      fontFamily: 'Inter, -apple-system, sans-serif',
      textAlign: 'center',
      lineHeight: 1.6,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_primary_cta',
    name: 'Primary Button - Get Started',
    type: 'button',
    x: 410,
    y: 340,
    width: 170,
    height: 46,
    content: '🚀 Sign Up Free',
    styles: {
      gradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
      color: '#ffffff',
      fontSize: 14,
      fontWeight: 600,
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#818cf8',
      boxShadow: '0 0 24px rgba(79, 70, 229, 0.5), 0 4px 12px rgba(0, 0, 0, 0.5)',
      opacity: 1,
      hoverEffect: 'lift',
      transitionDuration: 200,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: '🚀 Welcome to Craft Studio! Let us create your free account now.',
      buttonVariant: 'gradient',
      buttonIcon: 'arrow-right',
    },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_sec_link',
    name: 'Secondary Button - Learn More',
    type: 'button',
    x: 600,
    y: 340,
    width: 170,
    height: 46,
    content: '▶ Watch 2-Min Demo',
    styles: {
      backgroundColor: '#18181b',
      color: '#e4e4e7',
      fontSize: 14,
      fontWeight: 500,
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#3f3f46',
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.4)',
      opacity: 1,
      hoverEffect: 'scale',
      transitionDuration: 200,
    },
    role: 'button',
    behavior: {
      actionType: 'navigate-url',
      actionPayload: 'https://youtube.com',
      targetBlank: true,
      buttonVariant: 'outline',
    },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_hero_rating',
    name: 'Hero Rating Proof',
    type: 'text',
    x: 350,
    y: 400,
    width: 500,
    height: 24,
    content: '★★★★★ 4.9/5 from 2,500+ teams • No credit card required',
    styles: {
      color: '#818cf8',
      fontSize: 12,
      fontWeight: 500,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 14,
  },

  /* Product Showcase UI Mockup Card */
  {
    id: 'el_hero_mockup',
    name: 'UI Preview Showcase Card',
    type: 'container',
    x: 100,
    y: 440,
    width: 1000,
    height: 350,
    styles: {
      backgroundColor: '#0d1017',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#263148',
      boxShadow: '0 24px 60px rgba(0, 0, 0, 0.7), inset 0 1px 0 rgba(255, 255, 255, 0.08)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 15,
    children: [
      'el_mockup_bar',
      'el_mockup_stat1',
      'el_mockup_stat2',
      'el_mockup_stat3',
      'el_mockup_canvas_box',
    ],
  },
  {
    id: 'el_mockup_bar',
    name: 'Mockup Status Header',
    type: 'text',
    parentId: 'el_hero_mockup',
    x: 124,
    y: 460,
    width: 600,
    height: 24,
    content: '⚡ Real-Time App Analytics • 14,800 Active Users • 99.9% Uptime',
    styles: {
      color: '#34d399',
      fontSize: 12,
      fontFamily: "'JetBrains Mono', monospace",
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_mockup_stat1',
    name: 'Mockup Metric 1',
    type: 'container',
    parentId: 'el_hero_mockup',
    x: 124,
    y: 495,
    width: 290,
    height: 80,
    content: '⚡ Monthly Active Users\n148,200 (+34% MoM)',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#222a3d',
      color: '#ffffff',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 17,
  },
  {
    id: 'el_mockup_stat2',
    name: 'Mockup Metric 2',
    type: 'container',
    parentId: 'el_hero_mockup',
    x: 435,
    y: 495,
    width: 290,
    height: 80,
    content: '🎯 Form Conversion Rate\n64.8% (Industry Lead)',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#222a3d',
      color: '#ffffff',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 17,
  },
  {
    id: 'el_mockup_stat3',
    name: 'Mockup Metric 3',
    type: 'container',
    parentId: 'el_hero_mockup',
    x: 746,
    y: 495,
    width: 320,
    height: 80,
    content: '⏱ Page Speed Index\n0.28s (Grade A+ Lighthouse)',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#222a3d',
      color: '#ffffff',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 17,
  },
  {
    id: 'el_mockup_canvas_box',
    name: 'Mockup Interactive Artboard Preview',
    type: 'container',
    parentId: 'el_hero_mockup',
    x: 124,
    y: 590,
    width: 942,
    height: 180,
    content: '⬢ Live Artboard Canvas: Multi-Column Responsive Reflow Active • Zero-Latency Drag & Drop',
    styles: {
      backgroundColor: '#0a0d14',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: '#313e59',
      color: '#818cf8',
      fontSize: 13,
      textAlign: 'center',
      padding: 24,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 18,
  },

  /* ========================================================================== */
  /* 3. TRUSTED COMPANIES LOGOS STRIP                                           */
  /* ========================================================================== */
  {
    id: 'el_logos_title',
    name: 'Client Logos Section Title',
    type: 'text',
    x: 100,
    y: 830,
    width: 1000,
    height: 24,
    content: 'TRUSTED BY HIGH-VELOCITY TEAMS AT LEADING COMPANIES WORLDWIDE',
    styles: {
      color: '#64748b',
      fontSize: 11,
      fontWeight: 700,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_logo_1',
    name: 'Partner Logo - Vercel',
    type: 'container',
    x: 80,
    y: 868,
    width: 160,
    height: 48,
    content: '▲ Vercel',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#e2e8f0',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_logo_2',
    name: 'Partner Logo - Supabase',
    type: 'container',
    x: 270,
    y: 868,
    width: 160,
    height: 48,
    content: '⚡ Supabase',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#34d399',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_logo_3',
    name: 'Partner Logo - Stripe',
    type: 'container',
    x: 460,
    y: 868,
    width: 160,
    height: 48,
    content: '◈ Stripe',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#818cf8',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_logo_4',
    name: 'Partner Logo - Linear',
    type: 'container',
    x: 650,
    y: 868,
    width: 160,
    height: 48,
    content: '◆ Linear',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#c084fc',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_logo_5',
    name: 'Partner Logo - Raycast',
    type: 'container',
    x: 840,
    y: 868,
    width: 160,
    height: 48,
    content: '✦ Raycast',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#f87171',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_logo_6',
    name: 'Partner Logo - GitHub',
    type: 'container',
    x: 1030,
    y: 868,
    width: 130,
    height: 48,
    content: '◼ GitHub',
    styles: {
      backgroundColor: '#121624',
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#232c3f',
      color: '#ffffff',
      fontSize: 14,
      fontWeight: 600,
      textAlign: 'center',
      padding: 12,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },

  /* ========================================================================== */
  /* 4. FEATURES BENTO GRID (Includes el_card_1, el_card_2, el_card_3)         */
  /* ========================================================================== */
  {
    id: 'el_feat_badge',
    name: 'Features Section Badge',
    type: 'text',
    x: 480,
    y: 960,
    width: 240,
    height: 26,
    content: '⚡ CORE CAPABILITIES',
    styles: {
      color: '#38bdf8',
      fontSize: 11,
      fontWeight: 700,
      backgroundColor: 'rgba(14, 165, 233, 0.14)',
      borderColor: 'rgba(14, 165, 233, 0.35)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_feat_title',
    name: 'Features Section Title',
    type: 'text',
    x: 150,
    y: 995,
    width: 900,
    height: 44,
    content: 'Everything you need to ship high-converting web apps',
    styles: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_feat_sub',
    name: 'Features Section Subtitle',
    type: 'text',
    x: 200,
    y: 1045,
    width: 800,
    height: 34,
    content: 'No clunky plugins or bloated frameworks. Pure visual design with production code and real database tables.',
    styles: {
      color: '#94a3b8',
      fontSize: 14,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },

  // Feature Card 1
  {
    id: 'el_card_1',
    name: 'Features Card - Rocket',
    type: 'container',
    x: 80,
    y: 1100,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: {
      actionType: 'none',
      hoverStyles: {
        borderColor: '#6366f1',
        scale: 1.01,
      },
    },
    locked: false,
    zIndex: 9,
    children: ['el_card_1_icon', 'el_card_1_title', 'el_card_1_desc'],
  },
  {
    id: 'el_card_1_icon',
    name: 'Card 1 Icon',
    type: 'text',
    parentId: 'el_card_1',
    x: 104,
    y: 1124,
    width: 48,
    height: 48,
    content: '🚀',
    styles: {
      backgroundColor: 'rgba(99, 102, 241, 0.14)',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(99, 102, 241, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_card_1_title',
    name: 'Card 1 Title',
    type: 'text',
    parentId: 'el_card_1',
    x: 104,
    y: 1188,
    width: 260,
    height: 26,
    content: 'Visual Canvas Engine',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_card_1_desc',
    name: 'Card 1 Description',
    type: 'text',
    parentId: 'el_card_1',
    x: 104,
    y: 1220,
    width: 260,
    height: 60,
    content: 'Pixel-accurate positioning with smart snapping, flex sections, and zero-latency drag-and-drop manipulation.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },

  // Feature Card 2
  {
    id: 'el_card_2',
    name: 'Features Card - Grid',
    type: 'container',
    x: 445,
    y: 1100,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: {
      actionType: 'none',
      hoverStyles: {
        borderColor: '#38bdf8',
        scale: 1.01,
      },
    },
    locked: false,
    zIndex: 13,
    children: ['el_card_2_icon', 'el_card_2_title', 'el_card_2_desc'],
  },
  {
    id: 'el_card_2_icon',
    name: 'Card 2 Icon',
    type: 'text',
    parentId: 'el_card_2',
    x: 469,
    y: 1124,
    width: 48,
    height: 48,
    content: '⚏',
    styles: {
      backgroundColor: 'rgba(14, 165, 233, 0.14)',
      color: '#38bdf8',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(14, 165, 233, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 14,
  },
  {
    id: 'el_card_2_title',
    name: 'Card 2 Title',
    type: 'text',
    parentId: 'el_card_2',
    x: 469,
    y: 1188,
    width: 260,
    height: 26,
    content: 'Instant Supabase Database',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 15,
  },
  {
    id: 'el_card_2_desc',
    name: 'Card 2 Description',
    type: 'text',
    parentId: 'el_card_2',
    x: 469,
    y: 1220,
    width: 260,
    height: 60,
    content: 'Native Postgres cloud storage, user authentication, and real-time record synchronization built right into every form.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },

  // Feature Card 3
  {
    id: 'el_card_3',
    name: 'Features Card - Layers',
    type: 'container',
    x: 810,
    y: 1100,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: {
      actionType: 'none',
      hoverStyles: {
        borderColor: '#c084fc',
        scale: 1.01,
      },
    },
    locked: false,
    zIndex: 17,
    children: ['el_card_3_icon', 'el_card_3_title', 'el_card_3_desc'],
  },
  {
    id: 'el_card_3_icon',
    name: 'Card 3 Icon',
    type: 'text',
    parentId: 'el_card_3',
    x: 834,
    y: 1124,
    width: 48,
    height: 48,
    content: '▤',
    styles: {
      backgroundColor: 'rgba(168, 85, 247, 0.14)',
      color: '#c084fc',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(168, 85, 247, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 18,
  },
  {
    id: 'el_card_3_title',
    name: 'Card 3 Title',
    type: 'text',
    parentId: 'el_card_3',
    x: 834,
    y: 1188,
    width: 260,
    height: 26,
    content: 'Automatic Responsive Flow',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 19,
  },
  {
    id: 'el_card_3_desc',
    name: 'Card 3 Description',
    type: 'text',
    parentId: 'el_card_3',
    x: 834,
    y: 1220,
    width: 260,
    height: 60,
    content: 'Design once; layout engine intelligently reflows and stacks elements across desktop, laptop, tablet, and mobile views.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 20,
  },

  // Feature Card 4
  {
    id: 'el_card_4',
    name: 'Features Card - Lock',
    type: 'container',
    x: 80,
    y: 1340,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 21,
    children: ['el_card_4_icon', 'el_card_4_title', 'el_card_4_desc'],
  },
  {
    id: 'el_card_4_icon',
    name: 'Card 4 Icon',
    type: 'text',
    parentId: 'el_card_4',
    x: 104,
    y: 1364,
    width: 48,
    height: 48,
    content: '🔒',
    styles: {
      backgroundColor: 'rgba(234, 179, 8, 0.14)',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(234, 179, 8, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 22,
  },
  {
    id: 'el_card_4_title',
    name: 'Card 4 Title',
    type: 'text',
    parentId: 'el_card_4',
    x: 104,
    y: 1428,
    width: 260,
    height: 26,
    content: 'Strict Element Locking',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 23,
  },
  {
    id: 'el_card_4_desc',
    name: 'Card 4 Description',
    type: 'text',
    parentId: 'el_card_4',
    x: 104,
    y: 1460,
    width: 260,
    height: 60,
    content: 'Lock elements with 1-click to guarantee team design consistency while maintaining full inspection capabilities.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 24,
  },

  // Feature Card 5
  {
    id: 'el_card_5',
    name: 'Features Card - Code',
    type: 'container',
    x: 445,
    y: 1340,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 25,
    children: ['el_card_5_icon', 'el_card_5_title', 'el_card_5_desc'],
  },
  {
    id: 'el_card_5_icon',
    name: 'Card 5 Icon',
    type: 'text',
    parentId: 'el_card_5',
    x: 469,
    y: 1364,
    width: 48,
    height: 48,
    content: '⚡',
    styles: {
      backgroundColor: 'rgba(16, 185, 129, 0.14)',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(16, 185, 129, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 26,
  },
  {
    id: 'el_card_5_title',
    name: 'Card 5 Title',
    type: 'text',
    parentId: 'el_card_5',
    x: 469,
    y: 1428,
    width: 260,
    height: 26,
    content: 'Clean HTML/CSS Export',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 27,
  },
  {
    id: 'el_card_5_desc',
    name: 'Card 5 Description',
    type: 'text',
    parentId: 'el_card_5',
    x: 469,
    y: 1460,
    width: 260,
    height: 60,
    content: 'Export production-ready, accessible HTML5 and responsive CSS with zero framework lock-in whenever you need to ship.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 28,
  },

  // Feature Card 6
  {
    id: 'el_card_6',
    name: 'Features Card - Cloud',
    type: 'container',
    x: 810,
    y: 1340,
    width: 310,
    height: 220,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 29,
    children: ['el_card_6_icon', 'el_card_6_title', 'el_card_6_desc'],
  },
  {
    id: 'el_card_6_icon',
    name: 'Card 6 Icon',
    type: 'text',
    parentId: 'el_card_6',
    x: 834,
    y: 1364,
    width: 48,
    height: 48,
    content: '🌐',
    styles: {
      backgroundColor: 'rgba(236, 72, 153, 0.14)',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(236, 72, 153, 0.35)',
      fontSize: 22,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 30,
  },
  {
    id: 'el_card_6_title',
    name: 'Card 6 Title',
    type: 'text',
    parentId: 'el_card_6',
    x: 834,
    y: 1428,
    width: 260,
    height: 26,
    content: 'Custom Domain & Cloud SSL',
    styles: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 700,
      fontFamily: 'Inter, -apple-system, sans-serif',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 31,
  },
  {
    id: 'el_card_6_desc',
    name: 'Card 6 Description',
    type: 'text',
    parentId: 'el_card_6',
    x: 834,
    y: 1460,
    width: 260,
    height: 60,
    content: 'Deploy globally with edge caching, automated SSL certification, and lightning-fast CDN delivery worldwide.',
    styles: {
      color: '#8e8e93',
      fontSize: 13,
      lineHeight: 1.5,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 32,
  },

  /* ========================================================================== */
  /* 5. INTERACTIVE SIGN-UP & LEAD CAPTURE SECTION                              */
  /* ========================================================================== */
  {
    id: 'el_su_badge',
    name: 'Sign-Up Section Badge',
    type: 'text',
    x: 480,
    y: 1600,
    width: 240,
    height: 26,
    content: '✨ INSTANT ONBOARDING',
    styles: {
      color: '#a5b4fc',
      fontSize: 11,
      fontWeight: 700,
      backgroundColor: 'rgba(99, 102, 241, 0.16)',
      borderColor: 'rgba(99, 102, 241, 0.4)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_su_title',
    name: 'Sign-Up Section Title',
    type: 'text',
    x: 200,
    y: 1635,
    width: 800,
    height: 40,
    content: 'Create Your Free Account',
    styles: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_su_desc',
    name: 'Sign-Up Section Subtitle',
    type: 'text',
    x: 250,
    y: 1680,
    width: 700,
    height: 32,
    content: 'Start building high-converting landing pages in 30 seconds. No credit card required.',
    styles: {
      color: '#94a3b8',
      fontSize: 14,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_su_card',
    name: 'Sign-Up Form Card Container',
    type: 'container',
    x: 360,
    y: 1725,
    width: 480,
    height: 480,
    styles: {
      backgroundColor: '#121624',
      borderRadius: 20,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#263148',
      boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6), 0 0 40px rgba(99, 102, 241, 0.15)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 15,
    children: [
      'el_su_name_input',
      'el_su_email_input',
      'el_su_pwd_input',
      'el_su_submit_btn',
      'el_su_guarantees',
      'el_su_switch_link',
    ],
  },
  {
    id: 'el_su_name_input',
    name: 'Sign-Up Full Name Input',
    type: 'container',
    parentId: 'el_su_card',
    x: 395,
    y: 1760,
    width: 410,
    height: 44,
    content: 'Full Name (e.g. Jane Doe)',
    styles: {
      backgroundColor: '#0a0d14',
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#263148',
      color: '#64748b',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'input',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_su_email_input',
    name: 'Sign-Up Work Email Input',
    type: 'container',
    parentId: 'el_su_card',
    x: 395,
    y: 1820,
    width: 410,
    height: 44,
    content: 'Work Email (name@company.com)',
    styles: {
      backgroundColor: '#0a0d14',
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#263148',
      color: '#64748b',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'input',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_su_pwd_input',
    name: 'Sign-Up Password Input',
    type: 'container',
    parentId: 'el_su_card',
    x: 395,
    y: 1880,
    width: 410,
    height: 44,
    content: '•••••••• (at least 8 characters)',
    styles: {
      backgroundColor: '#0a0d14',
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#263148',
      color: '#64748b',
      fontSize: 13,
      padding: 12,
      opacity: 1,
    },
    role: 'input',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_su_submit_btn',
    name: 'Sign-Up Form Submit Button',
    type: 'button',
    parentId: 'el_su_card',
    x: 395,
    y: 1945,
    width: 410,
    height: 48,
    content: '🚀 Create Free Account Now →',
    styles: {
      gradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
      color: '#ffffff',
      fontSize: 14,
      fontWeight: 700,
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#818cf8',
      boxShadow: '0 4px 20px rgba(79, 70, 229, 0.5)',
      opacity: 1,
      hoverEffect: 'lift',
      transitionDuration: 200,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: '✨ Registration submitted! Welcome to Craft Studio. Account synced with Supabase Auth.',
    },
    locked: false,
    zIndex: 17,
  },
  {
    id: 'el_su_guarantees',
    name: 'Sign-Up Trust Badges',
    type: 'text',
    parentId: 'el_su_card',
    x: 395,
    y: 2010,
    width: 410,
    height: 28,
    content: '✓ 14-day free trial  •  ✓ Cancel anytime  •  ✓ SOC-2 Type II Certified',
    styles: {
      color: '#64748b',
      fontSize: 11,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 18,
  },
  {
    id: 'el_su_switch_link',
    name: 'Sign-In Switch Link',
    type: 'text',
    parentId: 'el_su_card',
    x: 395,
    y: 2045,
    width: 410,
    height: 24,
    content: 'Already have an account? Sign in here →',
    styles: {
      color: '#818cf8',
      fontSize: 12,
      fontWeight: 600,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'link',
    behavior: {
      actionType: 'alert',
      actionPayload: 'Navigating to Craft login portal...',
      hoverStyles: { color: '#a5b4fc' },
    },
    locked: false,
    zIndex: 18,
  },

  /* ========================================================================== */
  /* 6. SOCIAL PROOF & TESTIMONIALS                                            */
  /* ========================================================================== */
  {
    id: 'el_test_badge',
    name: 'Testimonials Section Badge',
    type: 'text',
    x: 480,
    y: 2260,
    width: 240,
    height: 26,
    content: '★ CLIENT PRAISE',
    styles: {
      color: '#f59e0b',
      fontSize: 11,
      fontWeight: 700,
      backgroundColor: 'rgba(245, 158, 11, 0.14)',
      borderColor: 'rgba(245, 158, 11, 0.35)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_test_title',
    name: 'Testimonials Section Title',
    type: 'text',
    x: 200,
    y: 2295,
    width: 800,
    height: 40,
    content: 'Loved by founders, designers & engineers',
    styles: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_test_1',
    name: 'Testimonial Card 1',
    type: 'container',
    x: 80,
    y: 2355,
    width: 310,
    height: 240,
    content: '★★★★★\n\n"This builder completely changed how our team prototypes and ships landing pages. We cut launch times from 2 weeks to 2 hours."\n\n— Sarah Lin • Head of Product, Vercel',
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      color: '#e2e8f0',
      fontSize: 13,
      lineHeight: 1.6,
      padding: 24,
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_test_2',
    name: 'Testimonial Card 2',
    type: 'container',
    x: 445,
    y: 2355,
    width: 310,
    height: 240,
    content: '★★★★★\n\n"The native Supabase database integration is magical. Form submissions and auth work right out of the box without writing backends."\n\n— Marcus Vance • Founder, TechFlow',
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      color: '#e2e8f0',
      fontSize: 13,
      lineHeight: 1.6,
      padding: 24,
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_test_3',
    name: 'Testimonial Card 3',
    type: 'container',
    x: 810,
    y: 2355,
    width: 310,
    height: 240,
    content: '★★★★★\n\n"The cleanest visual builder I have ever used. The responsive auto-reflow on phones is genuinely flawless and pixel-perfect."\n\n— Elena Rostova • Lead UI Engineer, Stripe',
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      color: '#e2e8f0',
      fontSize: 13,
      lineHeight: 1.6,
      padding: 24,
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },

  /* ========================================================================== */
  /* 7. TRANSPARENT 3-TIER PRICING TABLE                                        */
  /* ========================================================================== */
  {
    id: 'el_price_badge',
    name: 'Pricing Section Badge',
    type: 'text',
    x: 480,
    y: 2640,
    width: 240,
    height: 26,
    content: '💎 PRICING PLANS',
    styles: {
      color: '#a855f7',
      fontSize: 11,
      fontWeight: 700,
      backgroundColor: 'rgba(168, 85, 247, 0.14)',
      borderColor: 'rgba(168, 85, 247, 0.35)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_price_title',
    name: 'Pricing Section Title',
    type: 'text',
    x: 200,
    y: 2675,
    width: 800,
    height: 40,
    content: 'Simple, transparent pricing that scales',
    styles: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_price_1',
    name: 'Pricing Card - Starter',
    type: 'container',
    x: 80,
    y: 2735,
    width: 310,
    height: 380,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
    children: ['el_p1_title', 'el_p1_price', 'el_p1_features', 'el_p1_btn'],
  },
  {
    id: 'el_p1_title',
    name: 'Starter Plan Title',
    type: 'text',
    parentId: 'el_price_1',
    x: 104,
    y: 2760,
    width: 260,
    height: 28,
    content: 'Starter Plan',
    styles: { color: '#ffffff', fontSize: 18, fontWeight: 700, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p1_price',
    name: 'Starter Plan Price',
    type: 'text',
    parentId: 'el_price_1',
    x: 104,
    y: 2795,
    width: 260,
    height: 36,
    content: '$0 / month',
    styles: { color: '#ffffff', fontSize: 28, fontWeight: 800, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p1_features',
    name: 'Starter Plan Features',
    type: 'text',
    parentId: 'el_price_1',
    x: 104,
    y: 2840,
    width: 260,
    height: 170,
    content: '• 3 Active Web Projects\n• Visual Canvas Drag & Drop\n• Standard HTML/CSS Export\n• Responsive Viewports\n• Community Forum Support',
    styles: { color: '#94a3b8', fontSize: 13, lineHeight: 2.1, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p1_btn',
    name: 'Starter Plan Button',
    type: 'button',
    parentId: 'el_price_1',
    x: 104,
    y: 3045,
    width: 260,
    height: 42,
    content: 'Sign Up Free',
    styles: {
      backgroundColor: '#27272a',
      color: '#ffffff',
      borderRadius: 8,
      fontSize: 13,
      fontWeight: 600,
      opacity: 1,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: 'Starting with Craft Starter Plan! Free forever.',
    },
    locked: false,
    zIndex: 14,
  },

  {
    id: 'el_price_2',
    name: 'Pricing Card - Pro',
    type: 'container',
    x: 445,
    y: 2715,
    width: 310,
    height: 410,
    styles: {
      backgroundColor: '#151926',
      borderRadius: 16,
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: '#6366f1',
      boxShadow: '0 0 35px rgba(99, 102, 241, 0.35)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 15,
    children: ['el_p2_badge', 'el_p2_title', 'el_p2_price', 'el_p2_features', 'el_p2_btn'],
  },
  {
    id: 'el_p2_badge',
    name: 'Pro Plan Popular Badge',
    type: 'text',
    parentId: 'el_price_2',
    x: 469,
    y: 2730,
    width: 130,
    height: 22,
    content: '🔥 MOST POPULAR',
    styles: {
      backgroundColor: 'rgba(99, 102, 241, 0.3)',
      color: '#a5b4fc',
      fontSize: 10,
      fontWeight: 700,
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_p2_title',
    name: 'Pro Plan Title',
    type: 'text',
    parentId: 'el_price_2',
    x: 469,
    y: 2760,
    width: 260,
    height: 28,
    content: 'Pro Studio',
    styles: { color: '#ffffff', fontSize: 18, fontWeight: 700, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_p2_price',
    name: 'Pro Plan Price',
    type: 'text',
    parentId: 'el_price_2',
    x: 469,
    y: 2795,
    width: 260,
    height: 36,
    content: '$29 / month',
    styles: { color: '#ffffff', fontSize: 28, fontWeight: 800, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_p2_features',
    name: 'Pro Plan Features',
    type: 'text',
    parentId: 'el_price_2',
    x: 469,
    y: 2840,
    width: 260,
    height: 180,
    content: '• Unlimited Web Projects\n• Native Supabase Cloud DB\n• Custom Domains & SSL\n• Advanced Responsive Overrides\n• Priority 24/7 Chat Support\n• Full Standalone Code Export',
    styles: { color: '#c7d2fe', fontSize: 13, lineHeight: 2.1, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_p2_btn',
    name: 'Pro Plan Button',
    type: 'button',
    parentId: 'el_price_2',
    x: 469,
    y: 3055,
    width: 260,
    height: 44,
    content: 'Start 14-Day Free Trial →',
    styles: {
      gradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
      color: '#ffffff',
      borderRadius: 8,
      fontSize: 13,
      fontWeight: 700,
      boxShadow: '0 4px 16px rgba(79, 70, 229, 0.45)',
      opacity: 1,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: 'Starting Pro Studio 14-day free trial! No credit card needed.',
    },
    locked: false,
    zIndex: 17,
  },

  {
    id: 'el_price_3',
    name: 'Pricing Card - Enterprise',
    type: 'container',
    x: 810,
    y: 2735,
    width: 310,
    height: 380,
    styles: {
      backgroundColor: '#18181b',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#27272a',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
    children: ['el_p3_title', 'el_p3_price', 'el_p3_features', 'el_p3_btn'],
  },
  {
    id: 'el_p3_title',
    name: 'Enterprise Plan Title',
    type: 'text',
    parentId: 'el_price_3',
    x: 834,
    y: 2760,
    width: 260,
    height: 28,
    content: 'Enterprise',
    styles: { color: '#ffffff', fontSize: 18, fontWeight: 700, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p3_price',
    name: 'Enterprise Plan Price',
    type: 'text',
    parentId: 'el_price_3',
    x: 834,
    y: 2795,
    width: 260,
    height: 36,
    content: '$99 / month',
    styles: { color: '#ffffff', fontSize: 28, fontWeight: 800, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p3_features',
    name: 'Enterprise Plan Features',
    type: 'text',
    parentId: 'el_price_3',
    x: 834,
    y: 2840,
    width: 260,
    height: 170,
    content: '• Dedicated Postgres Cluster\n• Custom SSO & SAML Auth\n• 99.99% Guaranteed SLA\n• White-label Branding\n• Dedicated Solutions Engineer',
    styles: { color: '#94a3b8', fontSize: 13, lineHeight: 2.1, opacity: 1 },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 13,
  },
  {
    id: 'el_p3_btn',
    name: 'Enterprise Plan Button',
    type: 'button',
    parentId: 'el_price_3',
    x: 834,
    y: 3045,
    width: 260,
    height: 42,
    content: 'Contact Enterprise Sales',
    styles: {
      backgroundColor: '#27272a',
      color: '#ffffff',
      borderRadius: 8,
      fontSize: 13,
      fontWeight: 600,
      opacity: 1,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: 'Connecting you with a Craft Solutions Architect...',
    },
    locked: false,
    zIndex: 14,
  },

  /* ========================================================================== */
  /* 8. FREQUENTLY ASKED QUESTIONS (FAQ)                                        */
  /* ========================================================================== */
  {
    id: 'el_faq_badge',
    name: 'FAQ Section Badge',
    type: 'text',
    x: 480,
    y: 3180,
    width: 240,
    height: 26,
    content: '❓ COMMON INQUIRIES',
    styles: {
      color: '#94a3b8',
      fontSize: 11,
      fontWeight: 700,
      backgroundColor: 'rgba(148, 163, 184, 0.14)',
      borderColor: 'rgba(148, 163, 184, 0.35)',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 9999,
      textAlign: 'center',
      lineHeight: 2.2,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
  },
  {
    id: 'el_faq_title',
    name: 'FAQ Section Title',
    type: 'text',
    x: 200,
    y: 3215,
    width: 800,
    height: 40,
    content: 'Frequently Asked Questions',
    styles: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_faq_1',
    name: 'FAQ Item 1',
    type: 'container',
    x: 100,
    y: 3275,
    width: 1000,
    height: 85,
    content: '❓ Do I need coding experience to use Craft?\nNo coding knowledge is required. You can build, style, and connect databases visually, or inspect and export clean semantic HTML/CSS anytime.',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#242c3e',
      color: '#e2e8f0',
      fontSize: 14,
      lineHeight: 1.6,
      padding: 18,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_faq_2',
    name: 'FAQ Item 2',
    type: 'container',
    x: 100,
    y: 3375,
    width: 1000,
    height: 85,
    content: '❓ How does the Supabase authentication & database work?\nConnect your project URL and Anon Key in the Admin DB modal to automatically store sign-ups, forms, and user records in Postgres.',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#242c3e',
      color: '#e2e8f0',
      fontSize: 14,
      lineHeight: 1.6,
      padding: 18,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_faq_3',
    name: 'FAQ Item 3',
    type: 'container',
    x: 100,
    y: 3475,
    width: 1000,
    height: 85,
    content: '❓ Can I export pure semantic HTML/CSS and self-host?\nYes! Export 100% clean, semantic HTML and CSS with responsive media queries anytime with a single click. Zero platform lock-in.',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#242c3e',
      color: '#e2e8f0',
      fontSize: 14,
      lineHeight: 1.6,
      padding: 18,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },
  {
    id: 'el_faq_4',
    name: 'FAQ Item 4',
    type: 'container',
    x: 100,
    y: 3575,
    width: 1000,
    height: 85,
    content: '❓ Is there a free trial for the paid plans?\nYes, all paid plans include a risk-free 14-day trial with full feature access and no credit card required to start.',
    styles: {
      backgroundColor: '#141824',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#242c3e',
      color: '#e2e8f0',
      fontSize: 14,
      lineHeight: 1.6,
      padding: 18,
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 12,
  },

  /* ========================================================================== */
  /* 9. RADIANT CALL-TO-ACTION BANNER                                           */
  /* ========================================================================== */
  {
    id: 'el_cta_banner_card',
    name: 'Radiant Gradient CTA Banner',
    type: 'container',
    x: 60,
    y: 3710,
    width: 1080,
    height: 220,
    styles: {
      gradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #db2777 100%)',
      borderRadius: 20,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'rgba(255, 255, 255, 0.15)',
      boxShadow: '0 20px 50px rgba(79, 70, 229, 0.4)',
      opacity: 1,
    },
    role: 'card',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 15,
    children: ['el_cta_banner_title', 'el_cta_banner_sub', 'el_cta_banner_btn'],
  },
  {
    id: 'el_cta_banner_title',
    name: 'CTA Banner Title',
    type: 'text',
    parentId: 'el_cta_banner_card',
    x: 100,
    y: 3740,
    width: 1000,
    height: 40,
    content: 'Ready to Build Your Next High-Converting Web App?',
    styles: {
      color: '#ffffff',
      fontSize: 28,
      fontWeight: 800,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_cta_banner_sub',
    name: 'CTA Banner Subtitle',
    type: 'text',
    parentId: 'el_cta_banner_card',
    x: 100,
    y: 3785,
    width: 1000,
    height: 28,
    content: 'Join over 25,000+ creators building on the modern web today.',
    styles: {
      color: '#f1f5f9',
      fontSize: 15,
      textAlign: 'center',
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 16,
  },
  {
    id: 'el_cta_banner_btn',
    name: 'CTA Banner Sign Up Button',
    type: 'button',
    parentId: 'el_cta_banner_card',
    x: 450,
    y: 3830,
    width: 300,
    height: 48,
    content: '🚀 Sign Up Free & Get Started →',
    styles: {
      backgroundColor: '#ffffff',
      color: '#0f172a',
      fontSize: 14,
      fontWeight: 700,
      borderRadius: 8,
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
      opacity: 1,
      hoverEffect: 'lift',
      transitionDuration: 200,
    },
    role: 'button',
    behavior: {
      actionType: 'alert',
      actionPayload: '🚀 Welcome to Craft Studio! Starting your registration...',
    },
    locked: false,
    zIndex: 17,
  },

  /* ========================================================================== */
  /* 10. MODERN 4-COLUMN FOOTER                                                 */
  /* ========================================================================== */
  {
    id: 'el_footer_container',
    name: 'Modern 4-Column Footer',
    type: 'container',
    x: 40,
    y: 3980,
    width: 1120,
    height: 270,
    styles: {
      backgroundColor: '#0d1017',
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#1e2434',
      opacity: 1,
    },
    role: 'container',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 10,
    children: [
      'el_footer_col1',
      'el_footer_col2',
      'el_footer_col3',
      'el_footer_col4',
      'el_footer_copy',
    ],
  },
  {
    id: 'el_footer_col1',
    name: 'Footer Brand Column',
    type: 'text',
    parentId: 'el_footer_container',
    x: 70,
    y: 4010,
    width: 290,
    height: 140,
    content: '✦ CRAFT STUDIO\n\nThe modern visual website builder where canvas elements carry true semantic meaning and instant cloud data.',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      lineHeight: 1.8,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_footer_col2',
    name: 'Footer Product Column',
    type: 'text',
    parentId: 'el_footer_container',
    x: 420,
    y: 4010,
    width: 190,
    height: 140,
    content: 'Product\n\n• Visual Canvas\n• Responsive Flow\n• Supabase DB\n• Export HTML\n• Templates',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      lineHeight: 1.8,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_footer_col3',
    name: 'Footer Resources Column',
    type: 'text',
    parentId: 'el_footer_container',
    x: 670,
    y: 4010,
    width: 190,
    height: 140,
    content: 'Resources\n\n• Documentation\n• Video Guides\n• Community\n• API Reference\n• System Status',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      lineHeight: 1.8,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_footer_col4',
    name: 'Footer Company Column',
    type: 'text',
    parentId: 'el_footer_container',
    x: 910,
    y: 4010,
    width: 190,
    height: 140,
    content: 'Company\n\n• About Us\n• Customer Stories\n• Privacy Policy\n• Terms of Service\n• Contact Support',
    styles: {
      color: '#94a3b8',
      fontSize: 13,
      lineHeight: 1.8,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
  {
    id: 'el_footer_copy',
    name: 'Footer Copyright Note',
    type: 'text',
    parentId: 'el_footer_container',
    x: 70,
    y: 4185,
    width: 1060,
    height: 30,
    content: '© 2026 Craft Studio Inc. All rights reserved. Designed for visual precision and performance.',
    styles: {
      color: '#64748b',
      fontSize: 12,
      opacity: 1,
    },
    role: 'text',
    behavior: { actionType: 'none' },
    locked: false,
    zIndex: 11,
  },
];
